daemon {
  executors {
    default-executor {
      thread-count = 2
      thread-count = ${?DAEMON_DEFAULT_EXECUTOR_THREAD_COUNT}
      shutdown-grace-period = 1s
      shutdown-grace-period = ${?DAEMON_DEFAULT_EXECUTOR_SHUTDOWN_GRACE_PERIOD}
    }
    database-executor {
      thread-count = 16
      thread-count = ${?DAEMON_DATABASE_EXECUTOR_THREAD_COUNT}
      shutdown-grace-period = 1s
      shutdown-grace-period = ${?DAEMON_DATABASE_EXECUTOR_SHUTDOWN_GRACE_PERIOD}
    }
    io-dispatcher {
      thread-count = 16
      thread-count = ${?DAEMON_IO_DISPATCHER_THREAD_COUNT}
      shutdown-grace-period = 1s
      shutdown-grace-period = ${?DAEMON_IO_DISPATCHER_SHUTDOWN_GRACE_PERIOD}
    }
  }

  jobs {
    spotify-access-token-refresh {
      interval = 30m
      timeout = 5m
      retry {
        max-attempts = 3
        base-delay = 1s
        max-delay = 30s
        jitter-ratio = 0.2
      }
      batch-size = 50
    }

    followed-artists-sync-queue {
      interval = 1m
      timeout = 5m
      retry {
        max-attempts = 3
        base-delay = 1s
        max-delay = 30s
        jitter-ratio = 0.2
      }
    }

    followed-artists-sync {
      interval = 1h
      timeout = 10m
      retry {
        max-attempts = 3
        base-delay = 1s
        max-delay = 30s
        jitter-ratio = 0.2
      }
      batch-size = 25
      processing-lease = 1h
    }

    artist-release-sync-queue {
      interval = 1m
      timeout = 5m
      retry {
        max-attempts = 3
        base-delay = 1s
        max-delay = 30s
        jitter-ratio = 0.2
      }
    }

    artist-releases-sync {
      interval = 1m
      timeout = 10m
      retry {
        max-attempts = 3
        base-delay = 1s
        max-delay = 30s
        jitter-ratio = 0.2
      }
      batch-size = 200
      processing-lease = 1h
    }

    user-new-release-events-sync {
      interval = 1m
      timeout = 5m
      retry {
        max-attempts = 3
        base-delay = 1s
        max-delay = 30s
        jitter-ratio = 0.2
      }
      batch-size = 500
    }
  }
}
