rules = [
  DisableSyntax,
  RemoveUnused,
  ExplicitResultTypes,
  JakartaInjectGuice
]

ExplicitResultTypes.memberKind = [
  Def
]
ExplicitResultTypes.memberVisibility = [
  Public,
  Protected
]

lint.error = {
  includes = ".*"
  excludes = "UnusedScalafixSuppression"
}
