play.modules.enabled += "io.github.stoneream.dachshund.module.ApplicationModule"
play.modules.enabled += "io.github.stoneream.dachshund.module.ExecutorModule"
play.http.errorHandler = "io.github.stoneream.dachshund.http_error_handler.GlobalHttpErrorHandler"
play.http.filters = "io.github.stoneream.dachshund.filter.HttpFilters"

play.filters {
  hosts {
    allowed = ["localhost", ".local", "127.0.0.1"]
    allowed += ${?APP_ALLOWED_HOST}
  }

  cors {
    allowedOrigins = ["http://127.0.0.1:3000", "http://localhost:3000"]
    allowedOrigins += ${?CORS_ALLOWED_ORIGIN}
  }

  csp {
    nonce.enabled = false
    directives {
      default-src = "'self'"
      base-uri = "'self'"
      object-src = "'none'"
      frame-ancestors = "'none'"
      form-action = "'self'"
      script-src = "'self'"
      style-src = "'self'"
      img-src = "'self' data: https:"
      font-src = "'self' data:"
      connect-src = "'self'"
    }
  }
}

default-executor {
  type = Dispatcher
  fork-join-executor {
    parallelism-min = 8
    parallelism-factor = 1.0
    parallelism-max = 64
  }
  throughput = 1
}

database-executor {
  type = Dispatcher
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}

io-dispatcher {
  type = Dispatcher
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}
