flyway.url=jdbc:mysql://127.0.0.1:13306/dachshund_dev?characterEncoding=utf-8&characterSetResults=utf-8&allowPublicKeyRetrieval=true&useSSL=false
flyway.user=dachshund_dev
flyway.password=dachshund_dev
flyway.locations=filesystem:./migration
