package io.github.stoneream.dachshund.infra.db.writer

import io.github.stoneream.dachshund.infra.db.generated.{ArtistReleaseDbRow, ReleaseTrackDbRow}
import scalikejdbc.*

import javax.inject.{Inject, Singleton}

@Singleton
class ArtistReleasesWriter @Inject() () {
  def write(row: ArtistReleaseDbRow)(using DBSession): Long =
    sql"""
      insert into artist_release (
        spotify_release_code,
        source_spotify_artist_code,
        release_name,
        release_type,
        album_type,
        album_group,
        spotify_release_uri,
        spotify_url,
        href,
        primary_image_url,
        primary_image_height,
        primary_image_width,
        images_json,
        release_date_text,
        release_date_precision,
        release_date_at,
        total_tracks_count,
        label_name,
        normalized_label_name,
        external_ids_json,
        upc_code,
        ean_code,
        isrc_code,
        copyrights_json,
        available_markets_json,
        genres_json,
        restrictions_json,
        popularity,
        synced_at,
        created_at,
        updated_at,
        deleted_at,
        created_user,
        updated_user,
        deleted_user,
        deleted,
        lock_version
      ) values (
        {spotifyReleaseCode},
        {sourceSpotifyArtistCode},
        {releaseName},
        {releaseType},
        {albumType},
        {albumGroup},
        {spotifyReleaseUri},
        {spotifyUrl},
        {href},
        {primaryImageUrl},
        {primaryImageHeight},
        {primaryImageWidth},
        {imagesJson},
        {releaseDateText},
        {releaseDatePrecision},
        {releaseDateAt},
        {totalTracksCount},
        {labelName},
        {normalizedLabelName},
        {externalIdsJson},
        {upcCode},
        {eanCode},
        {isrcCode},
        {copyrightsJson},
        {availableMarketsJson},
        {genresJson},
        {restrictionsJson},
        {popularity},
        {syncedAt},
        {createdAt},
        {updatedAt},
        {deletedAt},
        {createdUser},
        {updatedUser},
        {deletedUser},
        {deleted},
        {lockVersion}
      )
    """
      .bindByName(
        "spotifyReleaseCode" -> row.spotifyReleaseCode,
        "sourceSpotifyArtistCode" -> row.sourceSpotifyArtistCode,
        "releaseName" -> row.releaseName,
        "releaseType" -> row.releaseType,
        "albumType" -> row.albumType,
        "albumGroup" -> row.albumGroup,
        "spotifyReleaseUri" -> row.spotifyReleaseUri,
        "spotifyUrl" -> row.spotifyUrl,
        "href" -> row.href,
        "primaryImageUrl" -> row.primaryImageUrl,
        "primaryImageHeight" -> row.primaryImageHeight,
        "primaryImageWidth" -> row.primaryImageWidth,
        "imagesJson" -> row.imagesJson,
        "releaseDateText" -> row.releaseDateText,
        "releaseDatePrecision" -> row.releaseDatePrecision,
        "releaseDateAt" -> row.releaseDateAt,
        "totalTracksCount" -> row.totalTracksCount,
        "labelName" -> row.labelName,
        "normalizedLabelName" -> row.normalizedLabelName,
        "externalIdsJson" -> row.externalIdsJson,
        "upcCode" -> row.upcCode,
        "eanCode" -> row.eanCode,
        "isrcCode" -> row.isrcCode,
        "copyrightsJson" -> row.copyrightsJson,
        "availableMarketsJson" -> row.availableMarketsJson,
        "genresJson" -> row.genresJson,
        "restrictionsJson" -> row.restrictionsJson,
        "popularity" -> row.popularity,
        "syncedAt" -> row.syncedAt,
        "createdAt" -> row.createdAt,
        "updatedAt" -> row.updatedAt,
        "deletedAt" -> row.deletedAt,
        "createdUser" -> row.createdUser,
        "updatedUser" -> row.updatedUser,
        "deletedUser" -> row.deletedUser,
        "deleted" -> row.deleted,
        "lockVersion" -> row.lockVersion
      )
      .updateAndReturnGeneratedKey
      .apply()

  def writeReleaseTrack(row: ReleaseTrackDbRow)(using DBSession): Long =
    sql"""
      insert into release_track (
        artist_release_id,
        spotify_track_code,
        track_name,
        spotify_track_uri,
        spotify_url,
        href,
        disc_number,
        track_number,
        duration_ms,
        explicit,
        is_playable,
        is_local,
        linked_from_spotify_track_code,
        linked_from_spotify_track_uri,
        preview_url,
        external_ids_json,
        isrc_code,
        ean_code,
        upc_code,
        available_markets_json,
        restrictions_json,
        popularity,
        synced_at,
        created_at,
        updated_at,
        deleted_at,
        created_user,
        updated_user,
        deleted_user,
        deleted,
        lock_version
      ) values (
        {artistReleaseId},
        {spotifyTrackCode},
        {trackName},
        {spotifyTrackUri},
        {spotifyUrl},
        {href},
        {discNumber},
        {trackNumber},
        {durationMs},
        {explicit},
        {isPlayable},
        {isLocal},
        {linkedFromSpotifyTrackCode},
        {linkedFromSpotifyTrackUri},
        {previewUrl},
        {externalIdsJson},
        {isrcCode},
        {eanCode},
        {upcCode},
        {availableMarketsJson},
        {restrictionsJson},
        {popularity},
        {syncedAt},
        {createdAt},
        {updatedAt},
        {deletedAt},
        {createdUser},
        {updatedUser},
        {deletedUser},
        {deleted},
        {lockVersion}
      )
    """
      .bindByName(
        "artistReleaseId" -> row.artistReleaseId,
        "spotifyTrackCode" -> row.spotifyTrackCode,
        "trackName" -> row.trackName,
        "spotifyTrackUri" -> row.spotifyTrackUri,
        "spotifyUrl" -> row.spotifyUrl,
        "href" -> row.href,
        "discNumber" -> row.discNumber,
        "trackNumber" -> row.trackNumber,
        "durationMs" -> row.durationMs,
        "explicit" -> row.explicit,
        "isPlayable" -> row.isPlayable,
        "isLocal" -> row.isLocal,
        "linkedFromSpotifyTrackCode" -> row.linkedFromSpotifyTrackCode,
        "linkedFromSpotifyTrackUri" -> row.linkedFromSpotifyTrackUri,
        "previewUrl" -> row.previewUrl,
        "externalIdsJson" -> row.externalIdsJson,
        "isrcCode" -> row.isrcCode,
        "eanCode" -> row.eanCode,
        "upcCode" -> row.upcCode,
        "availableMarketsJson" -> row.availableMarketsJson,
        "restrictionsJson" -> row.restrictionsJson,
        "popularity" -> row.popularity,
        "syncedAt" -> row.syncedAt,
        "createdAt" -> row.createdAt,
        "updatedAt" -> row.updatedAt,
        "deletedAt" -> row.deletedAt,
        "createdUser" -> row.createdUser,
        "updatedUser" -> row.updatedUser,
        "deletedUser" -> row.deletedUser,
        "deleted" -> row.deleted,
        "lockVersion" -> row.lockVersion
      )
      .updateAndReturnGeneratedKey
      .apply()
}
